import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        {/* <title>Create Next App</title>   */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>


      <main className={styles.main}>
        <img className={styles.myImg} src="/2.jpg"/>
        <h1 className={styles.title}> &lt;proshanto shaha /&gt; </h1>

        <p className={styles.description}> this site blogging site proshantomagni deleniti quod quam consequuntur! Commodi minima excepturi repudiandae velit hic maxime doloremque. Quaerat provident commodi consectetur veniam similique ad </p>

        <div className='blogs'>
            <h2 className={styles.h2}> Latest blogs</h2>
            <div>
              <h3 className={styles.h3}>how to learn javascript in 2022</h3>
              <p className={styles.p}>javascript language used to design to logic</p>
              <button className={styles.btn}>Read More</button>

            </div>
            <div>
              <h3 className={styles.h3}>how to learn javascript in 2022</h3>
              <p  className={styles.p}>javascript language used to design to logic</p>
              <button className={styles.btn}>Read More</button>
            </div>
            <div>
              <h3 className={styles.h3}>how to learn javascript in 2022</h3>
              <p  className={styles.p}>javascript language used to design to logic</p>
              <button className={styles.btn}>Read More</button>

            </div>
          </div>    
         
      </main>
    </div>
  )
}
