import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {
          `
          h2{
            font-size:39px

          }
          h3{
            font-size:28px
            
          }
          
          `
        }

      </style>
      <Head>
        {/* <title>Create Next App</title>   */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}> proshanto shaha</h1>
        <img className={styles.myImg} src="/2.jpg" width={237} height={158} />
        <p> this site blogging site proshanto </p>

        <div className='blogs'>
            <div className='blogItem'>
              <h1>how to learn javascript in 2022</h1>
              <p>javascript language used to design to logic</p>
            </div>
            <div className='blogItem'>
              <h1>how to learn javascript in 2022</h1>
              <p>javascript language used to design to logic</p>
            </div>
            <div className='blogItem'>
              <h1>how to learn javascript in 2022</h1>
              <p>javascript language used to design to logic</p>
            </div>
          </div>    
         
      </main>
    </div>
  )
}
