import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title>   */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    
      </Head>


      <nav className={styles.mainVav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>


      <main className={styles.main}>
        <h1 className={styles.title}> proshanto shaha</h1>
        <p> this site blogging site proshanto </p>

        <div className='blogs'>

          <h2> Popular Blogs</h2>
          <div className='blogItem'>
            <h3>  proshnto blogs</h3>
            <p> this  page your welcome</p>
          </div>
          <div className='blogItem'>
            <h3>  proshnto blogs</h3>
            <p> this  page your welcome</p>
          </div>
          <div className='blogItem'>
            <h3>  proshnto blogs</h3>
            <p> this  page your welcome</p>
          </div>
        </div>

      </main>
    </>
  )
}
